#!/bin/sh

mountpoint -q /proc || mount -t proc		proc /proc -o nosuid,noexec,nodev
mountpoint -q /sys	|| mount -t sysfs		sys /sys -o nosuid,noexec,nodev
mountpoint -q /run	|| mount -t tmpfs		run /run -o mode=0755,nosuid,nodev
mountpoint -q /dev  || mount -t devtmpfs	dev /dev -o mode=0755,nosuid

mkdir -p -m0755 /run/dinit /dev/pts /dev/shm

mountpoint -q /dev/pts || mount -n -t devpts devpts /dev/pts -o mode=0620,gid=5,nosuid,noexec
mountpoint -q /dev/shm || mount -n -t tmpfs shm /dev/shm -o mode=1777,nosuid,nodev

mountpoint -q /sys/kernel/security		|| mount -n -t securityfs securityfs /sys/kernel/security
mountpoint -q /sys/kernel/debug			|| mount -n -t debugfs debugfs /sys/kernel/debug -o nosuid,noexec,nodev
mountpoint -q /sys/kernel/config		|| mount -n -t configfs configfs /sys/kernel/config -o nosuid,noexec,nodev
mountpoint -q /sys/fs/pstore			|| mount -t pstore pstore /sys/fs/pstore -o nosuid,noexec,nodev
mountpoint -q /sys/fs/fuse/connections	|| \
	mount -n -t fusectl fusectl /sys/fs/fuse/connections -o nosuid,noexec,nodev

if [ -d /sys/firmware/efi ]; then
    if ! mountpoint -q /sys/firmware/efi/efivars; then
        if findmnt -n -o FSTYPE / | grep -q overlay; then
            mount -n -t efivarfs -o nosuid,noexec,nodev efivarfs /sys/firmware/efi/efivars
        else
            mount -n -t efivarfs -o ro,nosuid,noexec,nodev efivarfs /sys/firmware/efi/efivars
        fi
    fi
fi
